mesos:
  - version: 0.20.0
  - required_pkgs:
    - build-essential
    - openjdk-6-jdk
    - python-dev
    - python-boto
    - libcurl4-nss-dev
    - libsasl2-dev
    - maven
    - autoconf
    - libtool
    - libsvn-dev
    - libapr1-dev
